# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Edinburgh College of Art GitHub
email:
description: >- # this means to ignore newlines until "baseurl:"
  nec temere nec timide
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://Edinburgh-College-of-Art.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  Edinburgh-College-of-Art

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  # - jekyll-sitemap

header_pages:
  - about.md
  - workshops.md
  - blog.md

base_repo_url: "https://github.com/Edinburgh-College-of-Art/"

repos: [{name: "Architectural Design 3: Unit 3", repo: architectural-design-unit-3, site: true, url: ad3},
{name: "Connected Things", repo: Connected-Things, site: false},
{name: "Electronic Things", repo: Electronic-Things, site: false},
{name: "Histories and Futures of Technology", repo: Histories-and-Futures-of-Technology, site: false },
{name: "Dynamic Web Design", repo: dynamic-web-design, site: true, url: dwd},
{name: "Audio programming", repo: audio-programming, site: false  }
]

workshops: [{name: "Introduction to Git", repo: gitcarp, site: true, url: gitcarp},
{name: "Introduction to Arduino", repo: introduction-to-arduino, site: false},
{name: "Arduino for MaxMSP", repo: Arduino-for-Max, site: false},
{name: "Web Development", repo: web-development, site: false },
{name: "Audio Visualisation", repo: web-development, site: false }
]


collections:
  courses:
    output: true
  # workshops:
  #   output: false


gems: [jekyll_github_sample]
# paginate: 5

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
